export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED  = 'USER_LOGIN_FAILED'


export const USER_LOGOUT_REQUEST  = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_FAILED  = 'USER_LOGOUT_FAILED'
export const USER_LOGOUT_SUCCESS  = 'USER_LOGOUT_SUCCESS'


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED  = 'USER_REGISTER_FAILED'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAILED  = 'USER_DETAILS_FAILED'



export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAILED  = 'USER_UPDATE_PROFILE_FAILED'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_REQUEST'















/* Doctor Constants */ 

export const DOCTOR_LOGIN_REQUEST = 'DOCTOR_LOGIN_REQUEST'
export const DOCTOR_LOGIN_SUCCESS = 'DOCTOR_LOGIN_SUCCESS'
export const DOCTOR_LOGIN_FAILED  = 'DOCTOR_LOGIN_FAILED'


export const DOCTOR_REGISTER_REQUEST = 'DOCTOR_REGISTER_REQUEST'
export const DOCTOR_REGISTER_SUCCESS = 'DOCTOR_REGISTER_SUCCESS'
export const DOCTOR_REGISTER_FAILED  = 'DOCTOR_REGISTER_FAILED'


export const DOCTOR_LOGOUT_REQUEST = 'DOCTOR_LOGOUT_REQUEST'
export const DOCTOR_LOGOUT_SUCCESS = 'DOCTOR_LOGOUT_SUCCESS'
export const DOCTOR_LOGOUT_FAILED  = 'DOCTOR_LOGOUT_FAILED'

export const DOCTOR_DETAILS_REQUEST = 'DOCTOR_DETAILS_REQUEST'
export const DOCTOR_DETAILS_SUCCESS = 'DOCTOR_DETAILS_SUCCESS'
export const DOCTOR_DETAILS_FAILED  = 'DOCTOR_DETAILS_FAILED'



export const DOCTOR_UPDATE_PROFILE_REQUEST = 'DOCTOR_UPDATE_PROFILE_REQUEST'
export const DOCTOR_UPDATE_PROFILE_SUCCESS = 'DOCTOR_UPDATE_PROFILE_SUCCESS'
export const DOCTOR_UPDATE_PROFILE_FAILED  = 'DOCTOR_UPDATE_PROFILE_FAILED'
export const DOCTOR_UPDATE_PROFILE_RESET = 'DOCTOR_UPDATE_PROFILE_RESET'








